const nicknames = ["Sunny",
  "Sparky",
  "Luna",
  "Buddy",
  "Shadow",
  "Coco",
  "Rocky",
  "Max",
  "Stella",
  "Charlie",
  "Milo",
  "Rosie",
  "Oliver",
  "Daisy",
  "Teddy",
  "Conta no Orkut",
  "Nu Sertão",
  "SóXanaEAgua",
  "SawMasBom",
  "Dapra20comer",
  "NinguémJooga",
  "TatyComendo",
  "Tokagando",
  "Uhpapaichegou",
  "Intez Tino",
  "Cruizcredo",
  "Flamengolol",
  "Lord fralda",
  "SeuVagem",
  "Avestruz que te seduz",
  "Ouro que reluz",
  "Melado de óleo",
  "Tentei Comer quem leu",
  "Beijosmeliga",
  "Headshot grátis",
  "Sem Bala",
  "CertouMiseravi",
  "Naum Amola",
  "Cavalo amigável",
  "Morreu antes de ler",
  "100Nome",
  "TudoSpam",
  "Kharne Greylhada",
  "Sniper Boleto",
  "Capa Nera",
  "BatataSozinha",
  "FeraSokeRuim",
  "Amortyzador",
  "Parcyal Mente",
  "VlogImundo",
  "MortoComoFace",
  "After Eita",
  "Erro 504",
  "PuleiMorri",
  "iRuim 2.0",
  "LaggandoD+",
  "LixoDeQualidade",
  "Pirarucu Seboso",
  "MeusProbrema",
  "NickO Riginal",
  "ArsenalFunkeiro",
  "Rato Atomico",
  "Bispo Pelado",
  "Pablo Escovando",
  "Byata R3zando",
  "Cabo Nero",
  "Bruxopolis",
  "Sou1abismo",
  "Adaptoide",
  "DiegoDanger",
  "Dildo Baggins",
  "Riddickulo",
  "Vinho de Diezel",
  "Ze Morteiro",
  "Juan Casavelha",
  "Sayan Casual",
  "MineirodeChernobil",
  "Rick Jaimes",
  "Tirona Lapela",
  "JovemMistico",
  "Urso Vago",
  "MonkeeFeice",
  "Major Morte",
  "Tone Yorke",
  "Fredo Mercurio",
  "Davyd Boyeae",
  "Ivete Comgalo",
  "Eilish Rijinha",
  "Atom Jobine",
  "Abe Ração",
  "Wakanda emRuim",
  "Ace",
  "Adonis",
  "Badboy",
  "Bam Bam",
  "Bear",
  "Beast",
  "Beef",
  "Biggie",
  "Boner",
  "Boss",
  "Cowboy",
  "Daddy",
  "Elmo",
  "Gasoline",
  "Gangster",
  "Gizmo",
  "Godzilla",
  "Grandpa",
  "Grasshopper",
  "Handsome",
  "Harvard",
  "Hero",
  "Hercules",
  "Hollywood",
  "Hoss",
  "Hunk",
  "Jedi",
  "Macho",
  "Mayhem",
  "Motown",
  "Monster",
  "Moose",
  "Muscle",
  "Nemo",
  "Pickle",
  "Player",
  "Poker",
  "Pooh",
  "Pops",
  "Prince",
  "Pup",
  "Rockstar",
  "Romeo",
  "Scooter",
  "Skipper",
  "Sparkie",
  "Superfly",
  "Teddy",
  "Tiger",
  "Train",
  "Turtle",
  "Vegas",
  "Waldo",
  "Winner",
  "Cachorrão",
  "Gustavo da 12",
  "AnaChe",
  "Gironda",
  "Melissagata",
  "Aquidisgraça",
  "Martaonde",
  "Severinnis",
  "Diegostore",
  "LucasLucão",
  "Armigoonline",
  "Catlucia",
  "Tonymarrento",
  "Deuonda",
  "Metira",
  "Akinori",
  "Thor",
  "Maximus",
  "Exterminator",
  "Overtaker",
  "Naoki",
  "Sniper",
  "RockyBalboa",
  "Jaguar",
  "Torpedo",
  "Hazzard",
  "Satoshi",
  "Scorpion",
  "Mcgregor",
  "Cobra",
  "Falcão",
  "Prodigy",
  "Zombie",
  "Napoleon",
  "Coyote",
  "Rocks",
  "Whiskey",
  "CRMessi",
  "Go cu",
  "Painkiller",
  "Leon",
  "Kitsune",
  "Massacry",
  "Goblete",
  "TurboSquat",
  "HangLoose",
  "Mainframe",
  "CyberMancer",
  "Flint",
  "Pehkonen",
  "Sir Mavros",
  "PointlessShot",
  "Salty BR",
  "PanzerLow",
  "TrapTok",
  "ScourgeWolf",
  "SkyLord",
  "Drakkoo",
  "Guacanarix",
  "Anaphylaxis",
  "Claverol",
  "Ronak",
  "Thunder Cloak",
  "Nygrum",
  "Alcatrax",
  "Black Lot",
  "Othalium",
  "Onyx Stryker",
  "Braquialys",
  "Crixos",
  "HydroSnake",
  "CTrlAltSNiper",
  "Crassus",
  "Baron Zemek",
  "Rifleman AT",
  "HeatSyka",
  "Ariete Aereo",
  "BlackHearth",
  "Brock Blast",
  "Blood Vessel",
  "IceBerry",
  "Sakano",
  "Ahlkemysta",
  "SuzukiSamurai",
  "Tenso",
  "TreeSensa",
  "TheRAM",
  "Pinkie",
  "Alpina Aster",
  "Magahis",
  "Gale",
  "Nacht",
  "Nebel",
  "GrrrlPowa",
  "Polly Rocket",
  "ValsinhaVeneno",
  "Sara Sahara",
  "MoçaTaDiferente",
  "Cover Girl",
  "Girllirla",
  "NinjaKawai",
  "ByancaNoir",
  "Aguja",
  "Mika",
  "Nathy",
  "BeClare",
  "Maya",
  "Aziza",
  "Ostarha",
  "Labirinto de Pandora",
  "PinaColada",
  "Tempestade de Amor",
  "Sniper do Lar",
  "Girassol",
  "Cheetara",
  "Sheera",
  "Dona Flor",
  "PanificadoraOmega",
  "Menina Ideal",
  "Caramelo",
  "Aurora Aboreal",
  "Debie",
  "Bayssa",
  "Athenas",
  "Isis",
  "Olimpia",
  "Gaia",
  "Eris",
  "Gueidy",
  "Europa",
  "Clyrene",
  "Erika",
  "Javalina",
  "Katana",
  "Katrielly",
  "Themis",
  "Harmonia",
  "Ártemis",
  "RainGurl",
  "DropHottie",
  "Mihano",
  "PukkaPie",
  "IrisAzul",
  "Rosae",
  "Cardi C",
  "StutterBling",
  "R4taZana",
  "Barnacula",
  "BlekKween",
  "Strygga",
  "Razorina",
  "Blinka182",
  "BloodShed",
  "Urtyga",
  "CalfKilla",
  "SteinCastle",
  "CoachWhip",
  "Cypher",
  "Dial Murder",
  "Spectrum",
  "Amon Ka",
  "Moonstar",
  "DarkCyfra",
  "DeathTrap",
  "LifeLyne",
  "Navalha",
  "Foice",
  "Titannia",
  "Britania",
  "Magmana"
  ];

const tituloElement = document.getElementById("titulo");
const gerarBtn = document.getElementById("gerar-btn");
const mensagemElement = document.getElementById("mensagem");
const resultadoElement = document.getElementById("resultado");

let index = 0;

function escreverTitulo() {
  tituloElement.textContent = titulos[index];
  index++;
  if (index === titulos.length) {
    index = 0;
  }
}

gerarBtn.addEventListener("click", function() {
  const randomIndex = Math.floor(Math.random() * nicknames.length);
  const nickname = nicknames[randomIndex];
  
  mensagemElement.textContent = "Parabéns, seu nickname foi gerado!";
  resultadoElement.textContent = nickname;
});

setInterval(escreverTitulo, 500);

for (let i = 0; i < 30; i++) {
  const bolha = document.createElement("div");
  bolha.classList.add("bolha");
  bolha.style.left = Math.random() * 100 + "%";
  bolha.style.animationDelay = Math.random() * 5 + "s";
  document.body.appendChild(bolha);
}